feat: Add naming conventions to branches
Issue: #5

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,13 +10,32 @@ env:
   APP_NAME: habit-or-die
   JAVA_VERSION: 21
   DISTRIBUTION: 'temurin'
+  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
 
 jobs:
+  check-branch-name:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Validate branch name
+        run: |
+          branch_name=${BRANCH_NAME}
+          pattern="^(feature|bugfix|hotfix|release|experiment|task|epic|story|improvement|chore)\/HD-[0-9]+(-[a-z0-9-]+)?( [a-z0-9]+)*$"
+          
+          if ! [[ $branch_name =~ $pattern ]]; then
+            echo "Error: Branch name '$branch_name' does not match the required naming convention."
+            echo "Pattern: $pattern"
+            exit 1
+          fi
+
   build:
     runs-on: ubuntu-latest
+    needs: check-branch-name
 
     steps:
-      - name: Git clone
+      - name: Checkout code
         uses: actions/checkout@v4
 
       - name: "Set up JKD $JAVA_VERSION $DISTRIBUTION"
@@ -36,7 +55,7 @@ jobs:
     needs: build
 
     steps:
-      - name: Git clone
+      - name: Checkout code
         uses: actions/checkout@v4
 
       - name: "Set up JKD $JAVA_VERSION $DISTRIBUTION"
